name: Portfolio v2

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  validate-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Check & Build
        # Runs 'tsc -b' to ensure strict type compliance before building
        run: npm run build
